[build]
  command = "npm run build"
  publish = "dist"

[dev]
  publish = "dist"
  command = "npm run serve"

[[redirects]]
  from = "/latest"
  to = "/blog"
  
[[redirects]]
  from = "/blog/*"
  to = "/news/:splat"
